name: Publish Production Consultant Store
# This workflow is triggered on creation of releases on the master branch only.
on:
  release:
    types:
      - created
    branches:
      mock

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [14.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ matrix.node }}

    - name: npm cache
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install Stencil CLI Dependency
      run: npm install -g @bigcommerce/stencil-cli
      
    - name: Install Dependencies
      run: npm ci

    - name: Connect to store
      env:
        URL: ${{ secrets.ACCESS_URL_CONSULTANT_STORE_PRODUCTION }}
        TOKEN: ${{ secrets.ACCESS_TOKEN_CONSULTANT_STORE_PRODUCTION }}
      run: stencil init -u $URL -t $TOKEN -p 3000 -h https://api.bigcommerce.com

    - name: Publishing theme to Production, automatically deleting oldest theme if necessary
      run: stencil push -a Light
